version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER : sampleuser
      MYSQL_PASSWORD : changepassword105170
      MYSQL_DATABASE : project
      MYSQL_ROOT_PASSWORD: example
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db


